<?php echo Phalcon\Tag::stylesheetLink("${cdnUrl}/css/misc/about.css"); ?>
<div id="ribbon" style="height: 500px;"></div>
<div class="container">
	<div class="row-fluid">
		<div class="span9">
			<div id="main-content">
				<div class="section markdown">
					
				</div> <!-- .section -->
			</div> <!-- #main-content -->
		</div> <!-- .span9 -->
		<div class="span3">
			<div id="sidebar-nav">
				<h5><?php echo $localization['default.terms.terms']; ?></h5>
				<ul class="contents">
					<li><a href="#">1</a></li>
					<li><a href="#">2</a></li>
				</ul>
			</div> <!-- #sidebar-nav -->
		</div> <!-- .span3 -->
	</div> <!-- .row-fluid -->
</div> <!-- .container -->
