<?php echo Phalcon\Tag::stylesheetLink("${cdnUrl}/css/accounts/signin.css"); ?>
<div id="login">
    <h2><?php echo $localization['accounts.signin.signin']; ?></h2>
    <div class="alert alert-error hide"><?php echo $localization['accounts.login.incorrect-password']; ?></div>
    <?php if ( $isLoggedOut ): ?>
    <div class="alert alert-success"><?php echo $localization['accounts.login.sign-out']; ?></div> <!-- .alert-success -->
    <?php endif; ?>
    <form id="login-form" method="POST" onsubmit="onSubmit(); return false;">
        <p class="row-fluid">
            <label for="username"><?php echo $localization['accounts.signin.username']; ?></label>
            <input id="username" name="username" class="span12" type="text" maxlength="32">
        </p>
        <p class="row-fluid">
            <label for="password">
                <?php echo $localization['accounts.signin.password']; ?>
                <span class="pull-right">
                    <a href="<?php echo $this->url->get('/accounts/reset-password'); ?>">
                        <?php echo $localization['accounts.signin.forgot-password']; ?>
                    </a>
                </span>
            </label>
            <input id="password" name="password" class="span12" type="password" maxlength="16">
        </p>
        <p>
            <label for="remember-me">
                <input type="checkbox"> <?php echo $localization['accounts.signin.remember-me']; ?>
            </label>
        </p>
        <p>
            <button class="btn btn-primary btn-block" type="submit"><?php echo $localization['accounts.signin.signin']; ?></button>
        </p>
    </form> <!-- #login-form -->
    <p class="text-center">
        <?php echo $localization['accounts.login.dont-have-account']; ?><br>
        <a href="<?php echo $this->url->get('/accounts/signup'); ?>"><?php echo $localization['accounts.signin.create-account']; ?></a>
    </p>
</div>

<?php echo Phalcon\Tag::javascriptInclude("${cdnUrl}/js/md5.min.js", false); ?>
<script type="text/javascript">
    function onSubmit() {
        $('.alert-success').addClass('hide');
        $('.alert-error').addClass('hide');
        $('button[type=submit]').attr('disabled', 'disabled');
        $('button[type=submit]').html('<?php echo $localization['accounts.signin.please-wait']; ?>');
        
        var username   = $('#username').val(),
            password   = md5($('#password').val()),
            rememberMe = $('input#remember-me').is(':checked');
        
        $('#password').val(password);
        return doLoginAction(username, password, rememberMe);
    };
</script>
<script type="text/javascript">
    function doLoginAction(username, password, rememberMe) {
        var postData = {
            'username': username,
            'password': password,
            'rememberMe': rememberMe
        };
        
        $.ajax({
            type: 'POST',
            url: '<?php echo $this->url->get('/accounts/signin.action'); ?>',
            data: postData,
            dataType: 'JSON',
            success: function(result){
                return processLoginResult(result);
            }
        });
    }
</script>
<script type="text/javascript">
    function processLoginResult(result) {
        if ( result['isSuccessful'] ) {
            var forwardUrl = '<?php echo $forwardUrl; ?>' || '<?php echo $this->url->get('/'); ?>';
            window.location.href = forwardUrl;
        } else {
            $('#password').val('');
            $('.alert-error').removeClass('hide');
        }

        $('button[type=submit]').html('<?php echo $localization['accounts.signin.signin']; ?>');
        $('button[type=submit]').removeAttr('disabled');
    }
</script>