<?php echo Phalcon\Tag::stylesheetLink("{$cdnUrl}/css/dashboard/style.css?ver={$appVerion}"); ?>
<?php echo Phalcon\Tag::stylesheetLink("{$cdnUrl}/css/dashboard/products.css?ver={$appVerion}"); ?>
<div id="dashboard" class="container">
    <div class="row-fluid">
        <div id="sidebar" class="span4">
            <ul id="sidebar-nav">
                <li>
                    <a href="<?php echo $this->url->get('/dashboard/profile'); ?>"><?php echo $localization['dashboard.sidebar.profile']; ?></a>
                </li>
                <li class="active">
                    <a href="<?php echo $this->url->get('/dashboard/products'); ?>"><?php echo $localization['dashboard.sidebar.my-products']; ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url->get('/dashboard/issues'); ?>"><?php echo $localization['dashboard.sidebar.my-issues']; ?></a>
                </li>
            </ul>
        </div> <!-- #sidebar -->
        <div class="span8">
            <div id="main-content">
                <div class="row-fluid">
                    <div class="span6">
                        <h4><?php echo $localization['dashboard.products.my-products']; ?></h4>
                    </div> <!-- .span6 -->
                    <div class="span6 text-right">
                        <button id="new-product-button" class="btn btn-primary"><?php echo $localization['dashboard.products.new-product']; ?></button>
                    </div> <!-- .span6 -->
                </div> <!-- .row-fluid -->
                <p id="no-products" class="hide"><?php echo $localization['dashboard.products.no-products']; ?></p>
                <p id="loading" class="text-center"><img src="<?php echo $cdnUrl; ?>/img/loading.gif" alt=""></p>
                <ul id="product-list"></ul>
                <div id="pagination" class="pagination">
                    <ul></ul>
                </div> <!-- #pagination -->
            </div> <!-- #main-content -->
        </div> <!-- .span8 -->
    </div> <!-- .row-fluid -->
</div> <!-- .container -->

<div id="product-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h5></h5>
    </div> <!-- .modal-header -->
    <div class="modal-body">
        <div class="alert alert-error hide"></div> <!-- .alert-error -->
        <input id="product-id" name="product-id" type="hidden" />
        <p>
            <label for="product-name">
                <?php echo $localization['dashboard.products.product-name']; ?>
                <a href="javascript:void(0);" id="new-product-name-language" class="pull-right"><i class="fa fa-plus-circle"></i></a>
            </label>
            <ul id="product-names">
                <div class="row-fluid">
                    <div class="span4">
                        <select id="product-name-language" class="product-name-language">
                        <?php foreach ( $this->languages as $key => $value ): ?>
                            <option value="<?php echo $key; ?>" <?php echo ($language == $key ? 'selected' : ''); ?>><?php echo $value; ?></option>
                        <?php endforeach; ?>
                        </select>
                    </div> <!-- .span4 -->
                    <div class="span8">
                        <div class="control-group">
                            <input id="product-name" class="product-name span12" type="text" maxlength="64">
                        </div> <!-- .control-group -->
                    </div> <!-- .span8 -->
                </div> <!-- .row-fluid -->
            </ul>
        </p>
        <p class="row-fluid">
            <label for="product-category"><?php echo $localization['dashboard.products.product-category']; ?></label>
            <select id="product-category" name="product-category" class="span12">
            <?php foreach ( $productCategories as $productCategory ): ?>
            <?php 
                $DEFAULT_LANGUAGE     = 'en';
                $productCategoryNames = $productCategory['productCategoryName'];
                
                if ( array_key_exists($language, $productCategoryNames) ):
            ?>
                <option value="<?php echo $productCategory['productCategorySlug']; ?>"><?php echo $productCategoryNames[$language]; ?></option>
            <?php elseif ( array_key_exists($DEFAULT_LANGUAGE, $productCategoryNames) ): ?>
                <option value="<?php echo $productCategory['productCategorySlug']; ?>"><?php echo $productCategoryNames[$DEFAULT_LANGUAGE]; ?></option>
            <?php endif; ?>
            <?php endforeach; ?>
            </select>
        </p> <!-- .row-fluid -->
        <p class="row-fluid">
            <label for="product-logo-url"><?php echo $localization['dashboard.products.product-logo-url']; ?></label>
            <input id="product-logo-url" name="product-logo-url" class="span12" type="text" maxlength="256">
        </p> <!-- .row-fluid -->
        <p class="row-fluid">
            <label for="latest-version"><?php echo $localization['dashboard.products.latest-version']; ?></label>
            <input id="latest-version" name="latest-version" class="span12" type="text" maxlength="24">
        </p> <!-- .row-fluid -->
        <p class="row-fluid">
            <label for="product-url"><?php echo $localization['dashboard.products.product-url']; ?></label>
            <input id="product-url" name="product-url" class="span12" type="text" maxlength="256">
        </p> <!-- .row-fluid -->
        <p>
            <label for="product-prerequisite">
                <?php echo $localization['dashboard.products.product-prerequisite']; ?>
                <a href="javascript:void(0);" id="new-product-prerequisite-language" class="pull-right"><i class="fa fa-plus-circle"></i></a>
            </label>
            <ul id="product-prerequisites">
                <div class="row-fluid">
                    <div class="span4">
                        <select id="product-prerequisite-language" class="product-prerequisite-language">
                        <?php foreach ( $this->languages as $key => $value ): ?>
                            <option value="<?php echo $key; ?>" <?php echo ($language == $key ? 'selected' : ''); ?>><?php echo $value; ?></option>
                        <?php endforeach; ?>
                        </select>
                    </div> <!-- .span4 -->
                    <div class="span8">
                        <div class="control-group">
                            <input id="product-prerequisite" class="product-prerequisite span12" type="text" maxlength="256">
                        </div> <!-- .control-group -->
                    </div> <!-- .span8 -->
                </div> <!-- .row-fluid -->
            </ul>
        </p>
        <p>
            <label for="wmd-input">
                <?php echo $localization['dashboard.products.product-description']; ?>
                <a href="javascript:void(0);" id="new-product-description-language" class="pull-right"><i class="fa fa-plus-circle"></i></a>
            </label>
            <div id="product-descriptions">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#product-description-<?php echo $language; ?>-tab" data-toggle="tab"><?php echo $this->languages[$language]; ?></a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="product-description-<?php echo $language; ?>-tab">
                        <div class="row-fluid">
                            <textarea id="product-description-<?php echo $language; ?>" class="hide"></textarea>
                            <div id="markdown-editor">
                                <div class="wmd-panel">
                                    <div id="wmd-button-bar"></div> <!-- #wmd-button-bar -->
                                    <textarea id="wmd-input" class="wmd-input" placeholder="<?php echo $localization['dashboard.products.introduce-product']; ?>"></textarea>
                                </div> <!-- .wmd-panel -->
                                <div id="wmd-preview" class="wmd-panel wmd-preview"></div> <!-- .wmd-preview -->
                            </div> <!-- #markdown-editor -->
                        </div> <!-- .row-fluid -->
                    </div> <!-- .tab-pane -->
                </div> <!-- .tab-content -->
            </div> <!-- #product-descriptions -->
        </p>
    </div> <!-- .modal-body -->
    <div class="modal-footer">
        <input id="csrf-token" name="<?php echo $this->security->getTokenKey(); ?>" value="<?php echo $this->security->getToken(); ?>" type="hidden" />
        <button class="btn" data-dismiss="modal" aria-hidden="true"><?php echo $localization['dashboard.products.close']; ?></button>
        <button class="btn btn-primary"><?php echo $localization['dashboard.products.save-changes']; ?></button>
    </div> <!-- .modal-footer -->
</div> <!-- #product-modal -->

<script type="text/javascript">
    $.getScript('<?php echo $cdnUrl; ?>/js/markdown.min.js', function() {
        converter = Markdown.getSanitizingConverter();
        editor    = new Markdown.Editor(converter);
        editor.run();

        getProducts();
    });
</script>
<script type="text/javascript">
    function getProducts(pageNumber) {
        var productCategory = $('li.active', '#product-categories').attr('data-value'),
            keyword         = $('#keyword').val();

        if ( typeof(pageNumber) == 'undefined' ) {
            pageNumber = 1;
        }
        $('#no-products').addClass('hide');
        $('#product-list').addClass('hide');
        $('#pagination').addClass('hide');
        $('#loading').removeClass('hide');
        return getProductsAction(productCategory, keyword, pageNumber);
    }
</script>
<script type="text/javascript">
    function getProductsAction(productCategory, keyword, pageNumber) {
        var pageRequest = {
            'productCategory': productCategory,
            'keyword': keyword,
            'page': pageNumber,
        };
        $.ajax({
            type: 'GET',
            url: '<?php echo $this->url->get('/dashboard/getProducts.action'); ?>',
            data: pageRequest,
            dataType: 'JSON',
            success: function(result){
                return processProductsResult(result, pageNumber);
            }
        });
    }
</script>
<script type="text/javascript">
    function processProductsResult(result, currentPage) {
        $('#loading').addClass('hide');

        if ( !result['isSuccessful'] ) {
            $('#no-products').removeClass('hide');
        } else {
            $('#product-list').removeClass('hide');
            $('#pagination').removeClass('hide');
            displayProducts(result['products']);
            displayPagination(currentPage, result['totalPages']);
        }
    }
</script>
<script type="text/javascript">
    function displayProducts(products) {
        $('#product-list').empty();

        for ( var i = 0; i < products.length; ++ i ) {
            $('#product-list').append(
                getProductContent(products[i])
            );
        }
    }
</script>
<script type="text/javascript">
    function getProductContent(product) {
        var productTemplate = '<li class="product row-fluid" data-value="%s">' +
                              '    <div class="span3">' + 
                              '        <img src="%s" alt="Product Logo" />' +
                              '    </div>' +
                              '    <div class="span9">' +
                              '        <h5><a href="<?php echo $this->url->get('/product/') ?>%s">%s</a></h5>' +
                              '        <ul class="inline">' +
                              '            <li><i class="fa fa-list"></i> %s</li>' +
                              '            <li><i class="fa fa-ticket"></i> %s</li>' +
                              '            <li><i class="fa fa-bug"></i> %s <?php echo $localization['dashboard.products.issues-reported']; ?></li>' +
                              '        </ul>' +
                              '        <div class="markdown">%s</div>' +
                              '        <p class="edit-link"><a href="javascript:void(0)"><?php echo $localization['dashboard.products.edit']; ?></a></p>' + 
                              '    </div>' +
                              '</li> <!-- .product -->';

        return productTemplate.format(product['productId'], product['productLogo'], product['productId'], 
                product['productName'], product['productCategory']['productCategoryName'], product['latestVersion'], 
                product['issuesCount'], stripHtml(converter.makeHtml(product['description'].replace(/\\n/g, '\n'))));
    }
</script>
<script type="text/javascript">
    function stripHtml(str) {
        return str.replace(/<(?:.|\s)*?>/g, " ");
    }
</script>
<script type="text/javascript">
    function displayPagination(currentPage, totalPages) {
        $('#pagination > ul').empty();

        var lowerBound = currentPage - 5 > 0 ? currentPage - 5 : 1,
            upperBound = currentPage + 5 < totalPages ? currentPage + 5 : totalPages;
            paginationString  = '<li class="previous ' + ( currentPage > 1 ? '' : 'disabled') + '"><a href="#">&lt;</a></li>';

        for ( var i = lowerBound; i <= upperBound; ++ i ) {
            paginationString += '<li' + ( currentPage == i ? ' class="active"' : '' ) + '><a href="#">' + i + '</a></li>';
        }
        paginationString     += '<li class="next ' + ( currentPage < totalPages ? '' : 'disabled') + '"><a href="#">&gt;</a></li>';
        $('#pagination > ul').append(paginationString);
    }
</script>
<script type="text/javascript">
    $('#new-product-button').click(function() {
        $('h5', '#product-modal').html('<?php echo $localization['dashboard.products.new-product']; ?>');
        $('input#product-id, input[type=text], textarea', '#product-modal').val('');
        $('.row-fluid', 'ul#product-names').slice(1).remove();
        $('.row-fluid', 'ul#product-prerequisites').slice(1).remove();
        $('.nav-tabs li', '#product-modal').not('.active').remove();
        $('.tab-pane', '#product-modal').not('.active').remove();
        $('#wmd-preview').html('');
        $('.alert-error', '#product-modal').addClass('hide');

        $('#product-modal').modal({
            'backdrop': 'static'
        });
    });
</script>
<script type="text/javascript">
    $('#new-product-name-language').click(function() {
        $('#product-names').append(getMultiLanguageInputControlGroup('product-name', 64));
    });
</script>
<script type="text/javascript">
    $('#new-product-prerequisite-language').click(function() {
        $('#product-prerequisites').append(getMultiLanguageInputControlGroup('product-prerequisite', 256));
    });
</script>
<script type="text/javascript">
    $('#product-modal').delegate('.trash', 'click', function() {
        $(this).parent().remove();
    });
</script>
<script type="text/javascript">
    $('.nav-tabs', '#product-modal').delegate('li', 'click', function(e) {
        var currentActiveTabNav         = $('li.active', '#product-modal'),
            currentActiveTabName        = $('a', currentActiveTabNav).attr('href').substr(1),
            currentActiveTextareaName   = currentActiveTabName.substr(0, currentActiveTabName.length - 4),
            currentActiveTextarea       = $('#' + currentActiveTextareaName),
            currentClickTabNav          = $(this),
            currentClickTabName         = $('a', currentClickTabNav).attr('href').substr(1),
            currentClickTextareaName    = currentClickTabName.substr(0, currentClickTabName.length - 4),
            currentClickTextarea        = $('#' + currentClickTextareaName);

        $(currentActiveTextarea).val($('#wmd-input').val());
        $('#wmd-input').val($(currentClickTextarea).val());
        $('#wmd-preview').html(converter.makeHtml($('#wmd-input').val()));
        $('#markdown-editor').appendTo($('.row-fluid', '#' + currentClickTabName));
    });
</script>
<script type="text/javascript">
    $('#new-product-description-language').click(function() {
        var nextLanguage = getNextAvailableLanguage();

        if ( typeof(nextLanguage) != 'undefined' ) {
            $('.nav-tabs').append(getTabNavContent(nextLanguage));
            $('.tab-content').append(getTabPaneContent(nextLanguage));
        }
    });
</script>
<script type="text/javascript">
    function getNextAvailableLanguage() {
        var allLanguages = {
        <?php 
        $index = 0;
        foreach ( $this->languages as $key => $value ): ?>
            '<?php echo $key; ?>': '<?php echo $value; ?>'<?php echo (++ $index != count($this->languages) ? ',' : '' ); ?>
        <?php endforeach; ?>
        };
        var addedLanguages = [];
        $('.tab-pane', '.tab-content').each(function() {
            var tabPaneId    = $(this).attr('id'),
                languageName = tabPaneId.substr(20, tabPaneId.length - 24); 
            addedLanguages.push(languageName);
        });

        for ( var languageSlug in allLanguages ) {
            if ( !~addedLanguages.indexOf(languageSlug) ) {
                return {
                    'languageSlug': languageSlug,
                    'languageName': allLanguages[languageSlug]
                };
            }
        }
    }
</script>
<script type="text/javascript">
    $('#product-list').delegate('p.edit-link', 'click', function() {
        var productId = $(this).parent().parent().attr('data-value');
        return getProductAction(productId);
    });
</script>
<script type="text/javascript">
    function getProductAction(productId) {
        var pageRequest = {
            'productId': productId
        };
        $.ajax({
            type: 'GET',
            url: '<?php echo $this->url->get('/dashboard/getProduct.action'); ?>',
            data: pageRequest,
            dataType: 'JSON',
            success: function(result){
                if ( result['isSuccessful'] ) {
                    return processProductResult(result);
                } else {
                    alert('<?php echo $localization['dashboard.products.product-not-found']; ?>');
                }
            }
        });
    }
</script>
<script type="text/javascript">
    function processProductResult(result) {
        $('h5', '#product-modal').html('<?php echo $localization['dashboard.products.edit-product']; ?>');
        $('#product-id', '#product-modal').val(result['product']['productId']);
        $('#product-logo-url', '#product-modal').val(result['product']['productLogo']);
        $('#product-category', '#product-modal').val(result['product']['productCategory']['productCategorySlug']);
        $('#latest-version', '#product-modal').val(result['product']['latestVersion']);
        $('#product-url', '#product-modal').val(result['product']['productUrl']);
        setProductNames(result['product']['productName']);
        setProductPrerequisites(result['product']['prerequisites']);
        setProductDescription(result['product']['description']);

        $('#product-modal').modal({
            'backdrop': 'static'
        });
    }
</script>
<script type="text/javascript">
    function setProductNames(productNames) {
        $('.row-fluid', 'ul#product-names').slice(1).remove();

        var isFirstItem = true;
        for ( var languageSlug in productNames ) {
            if ( isFirstItem ) {
                isFirstItem = false;
                $('#product-name-language').val(languageSlug);
                $('#product-name').val(productNames[languageSlug]);
            } else {
                $('#product-names').append(getMultiLanguageInputControlGroup('product-name', 64, languageSlug, productNames[languageSlug]));
            }
        }
    }
</script>
<script type="text/javascript">
    function setProductPrerequisites(prerequisites) {
        $('.row-fluid', 'ul#product-prerequisites').slice(1).remove();

        var isFirstItem = true;
        for ( var languageSlug in prerequisites ) {
            if ( isFirstItem ) {
                isFirstItem = false;
                $('#product-prerequisite-language').val(languageSlug);
                $('#product-prerequisite').val(prerequisites[languageSlug]);
            } else {
                $('#product-prerequisites').append(getMultiLanguageInputControlGroup('product-prerequisite', 256, languageSlug, prerequisites[languageSlug]));
            }
        }
    }
</script>
<script type="text/javascript">
    function setProductDescription(description) {
        var allLanguages = {
        <?php 
        $index = 0;
        foreach ( $this->languages as $key => $value ): ?>
            '<?php echo $key; ?>': '<?php echo $value; ?>'<?php echo (++ $index != count($this->languages) ? ',' : '' ); ?>
        <?php endforeach; ?>
        };
        $('.nav-tabs li', '#product-modal').not('.active').remove();
        $('.tab-pane', '#product-modal').not('.active').remove();

        var isFirstItem = true;
        for ( var languageSlug in description ) {
            if ( isFirstItem ) {
                isFirstItem = false;
                $('.nav-tabs > li.active > a', '#product-modal').html(allLanguages[languageSlug]);
                $('.nav-tabs > li.active > a', '#product-modal').attr('href', '#product-description-%s-tab'.format(languageSlug));
                $('.tab-pane.active', '#product-modal').attr('id', 'product-description-%s-tab'.format(languageSlug));
                $('.tab-pane.active textarea.hide', '#product-modal').attr('id', 'product-description-%s'.format(languageSlug));
                $('.tab-pane.active textarea', '#product-modal').val(description[languageSlug])
                $('#wmd-preview').html(converter.makeHtml($('#wmd-input').val()));
            } else {
                var language = {
                    'languageSlug': languageSlug,
                    'languageName': allLanguages[languageSlug]
                };
                $('.nav-tabs').append(getTabNavContent(language));
                $('.tab-content').append(getTabPaneContent(language, description[languageSlug]));
            }
        }
    }
</script>
<script type="text/javascript">
    function getMultiLanguageInputControlGroup(controlName, maxLength, language, value) {
        var productNameControlGroup = '<div class="row-fluid">' +
                                      '    <div class="span4">' +
                                      '        <select class="%s-language">' +
                                      <?php foreach ( $this->languages as $key => $value ): ?>
                                      '            <option value="<?php echo $key; ?>" %s><?php echo $value; ?></option>' +
                                      <?php endforeach; ?>
                                      '        </select>' +
                                      '    </div> <!-- .span4 -->' +
                                      '    <div class="span7">' +
                                      '        <div class="control-group">' +
                                      '            <input class="%s span12" type="text" maxlength="%s" value="%s">' +
                                      '        </div> <!-- .control-group -->' +
                                      '    </div> <!-- .span7 -->' +
                                      '    <div class="span1 trash">' +
                                      '        <a href="javascript:void(0);"><i class="fa fa-trash"></i></a>' + 
                                      '    </div> <!-- .span1 -->' +
                                      '</div> <!-- .row-fluid -->';
        return productNameControlGroup.format(
            controlName, 
        <?php foreach ( $this->languages as $key => $value ): ?>
            language == '<?php echo $key; ?>' ? 'selected' : '',
        <?php endforeach; ?>
            controlName, maxLength, typeof(value) == 'undefined' ? '' : value
        );
    }
</script>
<script type="text/javascript">
    function getTabNavContent(language) {
        var tabNavContent = '<li><a href="#product-description-%s-tab" data-toggle="tab">%s</a></li>';
        return tabNavContent.format(language['languageSlug'], language['languageName']);
    }
</script>
<script type="text/javascript">
    function getTabPaneContent(language, value) {
        var tabPaneContent = '<div class="tab-pane" id="product-description-%s-tab">' +
                             '    <div class="row-fluid">' +
                             '        <textarea id="product-description-%s" class="hide">%s</textarea>' +
                             '    </div> <!-- .row-fluid -->' +
                             '</div> <!-- .tab-pane -->';
        return tabPaneContent.format(
            language['languageSlug'], language['languageSlug'], 
            typeof(value) == 'undefined' ? '' : value);
    }
</script>
<script type="text/javascript">
    $('.btn-primary', '#product-modal').click(function() {
        var productId       = $('#product-id').val(),
            productName     = getProductName(),
            productCategory = $('#product-category').val(),
            productLogoUrl  = $('#product-logo-url').val(),
            latestVersion   = $('#latest-version').val(), 
            productUrl      = $('#product-url').val(),
            prerequisites   = getPrerequisites(),
            description     = getDescription(),
            csrfKey         = $('#csrf-token').attr('name'),
            csrfValue       = $('#csrf-token').val();

        $('.alert-error', '#product-modal').addClass('hide');
        $('input, select, textarea').attr('disabled', 'disabled');
        $('.btn-primary', '#product-modal').attr('disabled', 'disabled');
        $('.btn-primary', '#product-modal').html('<?php echo $localization['dashboard.products.saving']; ?>');
        if ( productId == '' ) {
            return createProduct(productName, productCategory, productLogoUrl, latestVersion, productUrl, prerequisites, description, csrfKey, csrfValue);
        } else {
            return editProduct(productId, productName, productCategory, productLogoUrl, latestVersion, productUrl, prerequisites, description, csrfKey, csrfValue);
        }
    });
</script>
<script type="text/javascript">
    function getProductName() {
        var productNames = {};

        $('.row-fluid', '#product-names').each(function() {
            var language    = $('.product-name-language', $(this)).val(),
                productName = $('.product-name', $(this)).val();

            productNames[language] = productName;
        });
        return productNames;
    }
</script>
<script type="text/javascript">
    function getPrerequisites() {
        var prerequisites = {};

        $('.row-fluid', '#product-prerequisites').each(function() {
            var language        = $('.product-prerequisite-language', $(this)).val(),
                prerequisite    = $('.product-prerequisite', $(this)).val();

            prerequisites[language] = prerequisite;
        });
        return prerequisites;
    }
</script>
<script type="text/javascript">
    function getDescription() {
        $('textarea.hide', '.tab-pane.active').val($('#wmd-input').val());

        var descriptions = {};

        $('.tab-pane', '#product-descriptions').each(function() {
            var tabName     = $(this).attr('id'),
                language    = tabName.substr(20, tabName.length - 24),
                description = $('#product-description-' + language).val();

            descriptions[language] = description;
        });
        return descriptions;
    }
</script>
<script type="text/javascript">
    function createProduct(productName, productCategory, productLogoUrl, latestVersion, productUrl, prerequisites, description, csrfKey, csrfValue) {
        var postData = {
            'productName': JSON.stringify(productName),
            'productCategory': productCategory,
            'productLogoUrl': productLogoUrl,
            'latestVersion': latestVersion,
            'productUrl': productUrl,
            'prerequisites': JSON.stringify(prerequisites),
            'description': JSON.stringify(description)
        };
        postData[csrfKey] = csrfValue;

        $.ajax({
            type: 'POST',
            url: '<?php echo $this->url->get('/dashboard/createProduct.action'); ?>',
            data: postData,
            dataType: 'JSON',
            success: function(result) {
                return processCreateProductResult(result);
            }
        });
    }
</script>
<script type="text/javascript">
    function editProduct(productId, productName, productCategory, productLogoUrl, latestVersion, productUrl, prerequisites, description, csrfKey, csrfValue) {
        var postData = {
            'productId': productId,
            'productName': JSON.stringify(productName),
            'productCategory': productCategory,
            'productLogoUrl': productLogoUrl,
            'latestVersion': latestVersion,
            'productUrl': productUrl,
            'prerequisites': JSON.stringify(prerequisites),
            'description': JSON.stringify(description)
        };
        postData[csrfKey] = csrfValue;

        $.ajax({
            type: 'POST',
            url: '<?php echo $this->url->get('/dashboard/editProduct.action'); ?>',
            data: postData,
            dataType: 'JSON',
            success: function(result) {
                return processEditProductResult(result);
            }
        });
    }
</script>
<script type="text/javascript">
    function processCreateProductResult(result) {
        if ( result['isSuccessful'] ) {
            getProducts();
            $('#product-modal').modal('hide');
        } else {
            var errorMessage = getErrorMessage(result);
            
            $('.alert-error', '#product-modal').html(errorMessage);
            $('.alert-error', '#product-modal').removeClass('hide');
        }
        $('#csrf-token').attr('name', result['csrfTokenKey']);
        $('#csrf-token').val(result['csrfToken']);
        $('input, select, textarea').removeAttr('disabled');
        $('.btn-primary', '#product-modal').removeAttr('disabled');
        $('.btn-primary', '#product-modal').html('<?php echo $localization['dashboard.products.save-changes']; ?>');
    }
</script>
<script type="text/javascript">
    function processEditProductResult(result) {
        if ( result['isSuccessful'] ) {
            var currentPage = $('li.active > a', '#pagination').html();
            getProducts(currentPage);
            $('#product-modal').modal('hide');
        } else {
            var errorMessage = getErrorMessage(result);

            $('.alert-error', '#product-modal').html(errorMessage);
            $('.alert-error', '#product-modal').removeClass('hide');
        }
        $('#csrf-token').attr('name', result['csrfTokenKey']);
        $('#csrf-token').val(result['csrfToken']);
        $('input, select, textarea').removeAttr('disabled');
        $('.btn-primary', '#product-modal').removeAttr('disabled');
        $('.btn-primary', '#product-modal').html('<?php echo $localization['dashboard.products.save-changes']; ?>');
    }
</script>
<script type="text/javascript">
    function getErrorMessage(result) {
        var errorMessage  = '';

        if ( !result['isTokenValid'] ) {
            errorMessage += '<?php echo $localization['dashboard.products.invalid-token']; ?><br>';
        }
        if ( result.hasOwnProperty('isProductExists') && !result['isProductExists'] ) {
            errorMessage += '<?php echo $localization['dashboard.products.product-not-exists']; ?><br>';
        }
        if ( result.hasOwnProperty('isDeveloperLegal') && !result['isDeveloperLegal'] ) {
            errorMessage += '<?php echo $localization['dashboard.products.invalid-developer']; ?><br>';
        }
        if ( result['isProductNameEmpty'] ) {
            errorMessage += '<?php echo $localization['dashboard.products.product-name-empty']; ?><br>';
        } else if ( !result['isProductNameLegal'] ) {
            errorMessage += '<?php echo $localization['dashboard.products.product-name-illegal']; ?><br>';
        }
        if ( !result['isProductCategoryLegal'] ) {
            errorMessage += '<?php echo $localization['dashboard.products.product-category-illegal']; ?><br>';
        }
        if ( result['isProductLogoEmpty'] ) {
            errorMessage += '<?php echo $localization['dashboard.products.product-logo-empty']; ?><br>';
        } else if ( !result['isProductLogoLegal'] ) {
            errorMessage += '<?php echo $localization['dashboard.products.product-logo-illegal']; ?><br>';
        }
        if ( result['isLatestVersionEmpty'] ) {
            errorMessage += '<?php echo $localization['dashboard.products.product-version-empty']; ?><br>';
        } else if ( !result['isLatestVersionLegal'] ) {
            errorMessage += '<?php echo $localization['dashboard.products.product-version-illegal']; ?><br>';
        }
        if ( result['isProductUrlEmpty'] ) {
            errorMessage += '<?php echo $localization['dashboard.products.product-url-empty']; ?><br>';
        } else if ( !result['isProductUrlLegal'] ) {
            errorMessage += '<?php echo $localization['dashboard.products.product-url-illegal']; ?><br>';
        }
        if ( result['isPrerequisitesEmpty'] ) {
            errorMessage += '<?php echo $localization['dashboard.products.product-prerequisites-empty']; ?><br>';
        } else if ( !result['isPrerequisitesLegal'] ) {
            errorMessage += '<?php echo $localization['dashboard.products.product-prerequisites-illegal']; ?><br>';
        }
        if ( result['isDescriptionEmpty'] ) {
            errorMessage += '<?php echo $localization['dashboard.products.product-description-empty']; ?><br>';
        } else if ( !result['isDescriptionLegal'] ) {
            errorMessage += '<?php echo $localization['dashboard.products.product-description-illegal']; ?><br>';
        }
        return errorMessage;
    }
</script>