<?php echo Phalcon\Tag::stylesheetLink("{$cdnUrl}/css/dashboard/style.css?ver={$appVerion}"); ?>
<?php echo Phalcon\Tag::stylesheetLink("{$cdnUrl}/css/dashboard/products.css?ver={$appVerion}"); ?>
<div id="dashboard" class="container">
    <div class="row-fluid">
        <div id="sidebar" class="span4">
            <ul id="sidebar-nav">
                <li>
                    <a href="<?php echo $this->url->get('/dashboard/profile'); ?>"><?php echo $localization['dashboard.sidebar.profile']; ?></a>
                </li>
                <li class="active">
                    <a href="<?php echo $this->url->get('/dashboard/products'); ?>"><?php echo $localization['dashboard.sidebar.my-products']; ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url->get('/dashboard/issues'); ?>"><?php echo $localization['dashboard.sidebar.my-issues']; ?></a>
                </li>
            </ul>
        </div> <!-- #sidebar -->
        <div class="span8">
            <div id="main-content">
                <div class="row-fluid">
                    <div class="span6">
                        <h4><?php echo $localization['dashboard.products.my-products']; ?></h4>
                    </div> <!-- .span6 -->
                    <div class="span6 text-right">
                        <button id="new-product-button" class="btn btn-primary"><?php echo $localization['dashboard.products.new-product']; ?></button>
                    </div> <!-- .span6 -->
                </div> <!-- .row-fluid -->
                <p id="no-products" class="hide"><?php echo $localization['dashboard.products.no-products']; ?></p>
                <p id="loading" class="text-center"><img src="<?php echo $cdnUrl; ?>/img/loading.gif" alt=""></p>
                <ul id="product-list"></ul>
                <div id="pagination" class="pagination">
                    <ul></ul>
                </div> <!-- #pagination -->
            </div> <!-- #main-content -->
        </div> <!-- .span8 -->
    </div> <!-- .row-fluid -->
</div> <!-- .container -->

<div id="product-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h5></h5>
    </div> <!-- .modal-header -->
    <div class="modal-body">
        <div class="alert alert-error hide"></div> <!-- .alert-error -->
        <p>
            <label for="product-name">
                <?php echo $localization['dashboard.products.product-name']; ?>
                <a href="javascript:void(0);" id="new-product-name-language" class="pull-right"><i class="fa fa-plus-circle"></i></a>
            </label>
            <ul id="product-names">
                <div class="row-fluid">
                    <div class="span4">
                        <select class="product-name-language">
                        <?php foreach ( $this->languages as $key => $value ): ?>
                            <option value="<?php echo $key; ?>" <?php echo ($language == $key ? 'selected' : ''); ?>><?php echo $value; ?></option>
                        <?php endforeach; ?>
                        </select>
                    </div> <!-- .span4 -->
                    <div class="span8">
                        <div class="control-group">
                            <input id="product-name" class="product-name span12" type="text" maxlength="64">
                        </div> <!-- .control-group -->
                    </div> <!-- .span8 -->
                </div> <!-- .row-fluid -->
            </ul>
        </p>
        <p class="row-fluid">
            <label for="product-category"><?php echo $localization['dashboard.products.product-category']; ?></label>
            <select id="product-category" name="product-category" class="span12">
            <?php foreach ( $productCategories as $productCategory ): ?>
            <?php 
                $DEFAULT_LANGUAGE     = 'en';
                $productCategoryNames = $productCategory['productCategoryName'];
                
                if ( array_key_exists($language, $productCategoryNames) ):
            ?>
                <option value="<?php echo $productCategory['productCategorySlug']; ?>"><?php echo $productCategoryNames[$language]; ?></option>
            <?php elseif ( array_key_exists($DEFAULT_LANGUAGE, $productCategoryNames) ): ?>
                <option value="<?php echo $productCategory['productCategorySlug']; ?>"><?php echo $productCategoryNames[$DEFAULT_LANGUAGE]; ?></option>
            <?php endif; ?>
            <?php endforeach; ?>
            </select>
        </p> <!-- .row-fluid -->
        <p class="row-fluid">
            <label for="product-logo-url"><?php echo $localization['dashboard.products.product-logo-url']; ?></label>
            <input id="product-logo-url" name="product-logo-url" class="span12" type="text" maxlength="256">
        </p> <!-- .row-fluid -->
        <p class="row-fluid">
            <label for="latest-version"><?php echo $localization['dashboard.products.latest-version']; ?></label>
            <input id="latest-version" name="latest-version" class="span12" type="text" maxlength="24">
        </p> <!-- .row-fluid -->
        <p class="row-fluid">
            <label for="product-url"><?php echo $localization['dashboard.products.product-url']; ?></label>
            <input id="product-url" name="product-url" class="span12" type="text" maxlength="256">
        </p> <!-- .row-fluid -->
        <p>
            <label for="product-prerequisite">
                <?php echo $localization['dashboard.products.product-prerequisite']; ?>
                <a href="javascript:void(0);" id="new-product-prerequisite-language" class="pull-right"><i class="fa fa-plus-circle"></i></a>
            </label>
            <ul id="product-prerequisites">
                <div class="row-fluid">
                    <div class="span4">
                        <select class="product-prerequisite-language">
                        <?php foreach ( $this->languages as $key => $value ): ?>
                            <option value="<?php echo $key; ?>" <?php echo ($language == $key ? 'selected' : ''); ?>><?php echo $value; ?></option>
                        <?php endforeach; ?>
                        </select>
                    </div> <!-- .span4 -->
                    <div class="span8">
                        <div class="control-group">
                            <input id="product-prerequisite" class="product-prerequisite span12" type="text" maxlength="256">
                        </div> <!-- .control-group -->
                    </div> <!-- .span8 -->
                </div> <!-- .row-fluid -->
            </ul>
        </p>
        <p>
            <label for="wmd-input">
                <?php echo $localization['dashboard.products.product-description']; ?>
                <a href="javascript:void(0);" id="new-product-description-language" class="pull-right"><i class="fa fa-plus-circle"></i></a>
            </label>
            <div id="product-descriptions">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#product-description-<?php echo $language; ?>-tab" data-toggle="tab"><?php echo $this->languages[$language]; ?></a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="product-description-<?php echo $language; ?>-tab">
                        <div class="row-fluid">
                            <textarea id="product-description-<?php echo $language; ?>" class="hide"></textarea>
                            <div id="markdown-editor">
                                <div class="wmd-panel">
                                    <div id="wmd-button-bar"></div> <!-- #wmd-button-bar -->
                                    <textarea id="wmd-input" class="wmd-input" placeholder="<?php echo $localization['dashboard.products.introduce-product']; ?>"></textarea>
                                </div> <!-- .wmd-panel -->
                                <div id="wmd-preview" class="wmd-panel wmd-preview"></div> <!-- .wmd-preview -->
                            </div> <!-- #markdown-editor -->
                        </div> <!-- .row-fluid -->
                    </div> <!-- .tab-pane -->
                </div> <!-- .tab-content -->
            </div> <!-- #product-descriptions -->
        </p>
    </div> <!-- .modal-body -->
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><?php echo $localization['dashboard.products.close']; ?></button>
        <button class="btn btn-primary"><?php echo $localization['dashboard.products.save-changes']; ?></button>
    </div> <!-- .modal-footer -->
</div> <!-- #product-modal -->

<script type="text/javascript">
    $.getScript('<?php echo $cdnUrl; ?>/js/markdown.min.js', function() {
        converter = Markdown.getSanitizingConverter();
        editor    = new Markdown.Editor(converter);
        editor.run();

        getProducts();
    });
</script>
<script type="text/javascript">
    function getProducts(pageNumber) {
        var productCategory = $('li.active', '#product-categories').attr('data-value'),
            keyword         = $('#keyword').val();

        if ( typeof(pageNumber) == 'undefined' ) {
            pageNumber = 1;
        }
        $('#no-products').addClass('hide');
        $('#product-list').addClass('hide');
        $('#pagination').addClass('hide');
        $('#loading').removeClass('hide');
        return getProductsAction(productCategory, keyword, pageNumber);
    }
</script>
<script type="text/javascript">
    function getProductsAction(productCategory, keyword, pageNumber) {
        var pageRequest = {
            'productCategory': productCategory,
            'keyword': keyword,
            'page': pageNumber,
        };
        $.ajax({
            type: 'GET',
            url: '<?php echo $this->url->get('/dashboard/getProducts.action'); ?>',
            data: pageRequest,
            dataType: 'JSON',
            success: function(result){
                return processProductsResult(result, pageNumber);
            }
        });
    }
</script>
<script type="text/javascript">
    function processProductsResult(result, currentPage) {
        $('#loading').addClass('hide');

        if ( !result['isSuccessful'] ) {
            $('#no-products').removeClass('hide');
        } else {
            $('#product-list').removeClass('hide');
            $('#pagination').removeClass('hide');
            displayProducts(result['products']);
            displayPagination(currentPage, result['totalPages']);
        }
    }
</script>
<script type="text/javascript">
    function displayProducts(products) {
        $('#product-list').empty();

        for ( var i = 0; i < products.length; ++ i ) {
            $('#product-list').append(
                getProductContent(products[i])
            );
        }
    }
</script>
<script type="text/javascript">
    function getProductContent(product) {
        var productTemplate = '<li class="product row-fluid" data-value="%s">' +
                              '    <div class="span3">' + 
                              '        <img src="%s" alt="Product Logo" />' +
                              '    </div>' +
                              '    <div class="span9">' +
                              '        <h5><a href="<?php echo $this->url->get('/product/') ?>%s">%s</a></h5>' +
                              '        <ul class="inline">' +
                              '            <li><i class="fa fa-list"></i> %s</li>' +
                              '            <li><i class="fa fa-ticket"></i> %s</li>' +
                              '            <li><i class="fa fa-bug"></i> %s <?php echo $localization['dashboard.products.issues-reported']; ?></li>' +
                              '        </ul>' +
                              '        <div class="markdown">%s</div>' +
                              '        <p class="edit-link"><a href="javascript:void(0)"><?php echo $localization['dashboard.products.edit']; ?></a></p>' + 
                              '    </div>' +
                              '</li> <!-- .product -->';

        return productTemplate.format(product['productId'], product['productLogo'], product['productId'], 
                product['productName'], product['productCategory']['productCategoryName'], product['latestVersion'], 
                product['issuesCount'], stripHtml(converter.makeHtml(product['description'].replace(/\\n/g, '\n'))));
    }
</script>
<script type="text/javascript">
    function stripHtml(str) {
        return str.replace(/<(?:.|\s)*?>/g, " ");
    }
</script>
<script type="text/javascript">
    function displayPagination(currentPage, totalPages) {
        $('#pagination > ul').empty();

        var lowerBound = currentPage - 5 > 0 ? currentPage - 5 : 1,
            upperBound = currentPage + 5 < totalPages ? currentPage + 5 : totalPages;
            paginationString  = '<li class="previous ' + ( currentPage > 1 ? '' : 'disabled') + '"><a href="#">&lt;</a></li>';

        for ( var i = lowerBound; i <= upperBound; ++ i ) {
            paginationString += '<li' + ( currentPage == i ? ' class="active"' : '' ) + '><a href="#">' + i + '</a></li>';
        }
        paginationString     += '<li class="next ' + ( currentPage < totalPages ? '' : 'disabled') + '"><a href="#">&gt;</a></li>';
        $('#pagination > ul').append(paginationString);
    }
</script>
<script type="text/javascript">
    $('#new-product-button').click(function() {
        $('h5', '#product-modal').html('<?php echo $localization['dashboard.products.new-product']; ?>');
        $('input, textarea', '#product-modal').val('');

        $('#product-modal').modal({
            'backdrop': 'static'
        });
    });
</script>
<script type="text/javascript">
    $('#product-list').delegate('p.edit-link', 'click', function() {
        var productId = $(this).parent().parent().attr('data-value');
        return getProductAction(productId);
    });
</script>
<script type="text/javascript">
    function getProductAction(productId) {
        var pageRequest = {
            'productId': productId
        };
        $.ajax({
            type: 'GET',
            url: '<?php echo $this->url->get('/dashboard/getProduct.action'); ?>',
            data: pageRequest,
            dataType: 'JSON',
            success: function(result){
                if ( result['isSuccessful'] ) {
                    return processProductResult(result);
                } else {
                    alert('<?php echo $localization['dashboard.products.product-not-found']; ?>');
                }
            }
        });
    }
</script>
<script type="text/javascript">
    function processProductResult(result) {
        $('h5', '#product-modal').html('<?php echo $localization['dashboard.products.edit-product']; ?>');

        $('#product-modal').modal({
            'backdrop': 'static'
        });
    }
</script>
<script type="text/javascript">
    $('#new-product-name-language').click(function() {
        $('#product-names').append(getMultiLanguageInputControlGroup('product-name', 64));
    });
</script>
<script type="text/javascript">
    $('#new-product-prerequisite-language').click(function() {
        $('#product-prerequisites').append(getMultiLanguageInputControlGroup('product-prerequisite', 256));
    });
</script>
<script type="text/javascript">
    $('#product-modal').delegate('.trash', 'click', function() {
        $(this).parent().remove();
    });
</script>
<script type="text/javascript">
    function getMultiLanguageInputControlGroup(controlName, maxLength, language, value) {
        var productNameControlGroup = '<div class="row-fluid">' +
                                      '    <div class="span4">' +
                                      '        <select class="%s-language">' +
                                      <?php foreach ( $this->languages as $key => $value ): ?>
                                      '            <option value="<?php echo $key; ?>" %s><?php echo $value; ?></option>' +
                                      <?php endforeach; ?>
                                      '        </select>' +
                                      '    </div> <!-- .span4 -->' +
                                      '    <div class="span7">' +
                                      '        <div class="control-group">' +
                                      '            <input class="%s span12" type="text" maxlength="%s" value="%s">' +
                                      '        </div> <!-- .control-group -->' +
                                      '    </div> <!-- .span7 -->' +
                                      '    <div class="span1 trash">' +
                                      '        <a href="javascript:void(0);"><i class="fa fa-trash"></i></a>' + 
                                      '    </div> <!-- .span1 -->' +
                                      '</div> <!-- .row-fluid -->';
        return productNameControlGroup.format(
            controlName, 
        <?php foreach ( $this->languages as $key => $value ): ?>
            language == '<?php echo $key; ?>',
        <?php endforeach; ?>
            controlName, maxLength, typeof(value) == 'undefined' ? '' : value
        );
    }
</script>
<script type="text/javascript">
    $('.nav-tabs', '#product-modal').delegate('li', 'click', function(e) {
        var currentActiveTabNav         = $('li.active', '#product-modal'),
            currentActiveTabName        = $('a', currentActiveTabNav).attr('href').substr(1),
            currentActiveTextareaName   = currentActiveTabName.substr(0, currentActiveTabName.length - 4),
            currentActiveTextarea       = $('#' + currentActiveTextareaName),
            currentClickTabNav          = $(this),
            currentClickTabName        = $('a', currentClickTabNav).attr('href').substr(1),
            currentClickTextareaName   = currentClickTabName.substr(0, currentClickTabName.length - 4),
            currentClickTextarea       = $('#' + currentClickTextareaName);

        $(currentActiveTextarea).val($('#wmd-input').val());
        $('#wmd-input').val($(currentClickTextarea).val());
        $('#wmd-preview').html(converter.makeHtml($('#wmd-input').val()));
        $('#markdown-editor').appendTo($('.row-fluid', '#' + currentClickTabName));
    });
</script>
<script type="text/javascript">
    $('#new-product-description-language').click(function() {
        var nextLanguage = getNextAvailableLanguage();

        if ( typeof(nextLanguage) != 'undefined' ) {
            $('.nav-tabs').append(getTabNavContent(nextLanguage));
            $('.tab-content').append(getTabPaneContent(nextLanguage));
        }
    });
</script>
<script type="text/javascript">
    function getNextAvailableLanguage() {
        var allLanguages = {
        <?php 
        $index = 0;
        foreach ( $this->languages as $key => $value ): ?>
            '<?php echo $key; ?>': '<?php echo $value; ?>'<?php echo (++ $index != count($this->languages) ? ',' : '' ); ?>
        <?php endforeach; ?>
        };
        var addedLanguages = [];
        $('.tab-pane', '.tab-content').each(function() {
            var tabPaneId    = $(this).attr('id'),
                languageName = tabPaneId.substr(20, tabPaneId.length - 24); 
            addedLanguages.push(languageName);
        });

        for ( var language in allLanguages ) {
            if ( !~addedLanguages.indexOf(language) ) {
                return {
                    'languageSlug': language,
                    'languageName': allLanguages[language]
                };
            }
        }
    }
</script>
<script type="text/javascript">
    function getTabNavContent(nextLanguage) {
        var tabNavContent = '<li><a href="#product-description-%s-tab" data-toggle="tab">%s</a></li>';
        return tabNavContent.format(nextLanguage['languageSlug'], nextLanguage['languageName']);
    }
</script>
<script type="text/javascript">
    function getTabPaneContent(nextLanguage) {
        var tabPaneContent = '<div class="tab-pane" id="product-description-%s-tab">' +
                             '    <div class="row-fluid">' +
                             '        <textarea id="product-description-%s" class="hide"></textarea>' +
                             '    </div> <!-- .row-fluid -->' +
                             '</div> <!-- .tab-pane -->';
        return tabPaneContent.format(nextLanguage['languageSlug'], nextLanguage['languageSlug']);
    }
</script>