<?php echo Phalcon\Tag::stylesheetLink("{$cdnUrl}/css/dashboard/style.css?ver={$appVerion}"); ?>
<?php echo Phalcon\Tag::stylesheetLink("{$cdnUrl}/css/dashboard/issues.css?ver={$appVerion}"); ?>
<div id="dashboard" class="container">
    <div class="row-fluid">
        <div id="sidebar" class="span4">
            <ul id="sidebar-nav">
                <li>
                    <a href="<?php echo $this->url->get('/dashboard/profile'); ?>"><?php echo $localization['dashboard.sidebar.profile']; ?></a>
                </li>
                <li>
                    <a href="<?php echo $this->url->get('/dashboard/products'); ?>"><?php echo $localization['dashboard.sidebar.my-products']; ?></a>
                </li>
                <li class="active">
                    <a href="<?php echo $this->url->get('/dashboard/issues'); ?>"><?php echo $localization['dashboard.sidebar.my-issues']; ?></a>
                    <ul class="sub-nav">
                        <li class="active">
                            <a href="<?php echo $this->url->get('/dashboard/issues/received'); ?>"><?php echo $localization['dashboard.sidebar-received-issues']; ?></a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url->get('/dashboard/issues/submitted'); ?>"><?php echo $localization['dashboard.sidebar-submitted-issues']; ?></a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div> <!-- #sidebar -->
        <div class="span8">
            <div id="main-content">
                <div class="row-fluid">
                    <div class="span6">
                        <h4><?php echo $localization['dashboard.issues.quick-search']; ?></h4>
                    </div> <!-- .span6 -->
                    <div class="span6 text-right">
                        <button id="issue-filter" class="btn btn-primary"><?php echo $localization['dashboard.issues.filter']; ?></button>
                    </div> <!-- .span6 -->
                </div> <!-- .row-fluid -->
                <div class="row-fluid">
                    <div class="span4">
                        <select id="product">
                            <option value=""><?php echo $localization['dashboard.issues.product-name']; ?></option>
                        <?php foreach ( $products as $product ): ?>
                            <option value="<?php echo $product['productId']; ?>"><?php echo $product['productName']; ?></option>
                        <?php endforeach; ?>
                        </select>
                    </div> <!-- .span4 -->
                    <div class="span4">
                        <select id="issue-category">
                            <option value=""><?php echo $localization['dashboard.issues.issue-category']; ?></option>
                        <?php foreach ( $issueCategories as $issueCategory ): ?>
                            <option value="<?php echo $issueCategory['issueCategorySlug']; ?>"><?php echo $issueCategory['issueCategoryName']; ?></option>
                        <?php endforeach; ?>
                        </select>
                    </div> <!-- .span4 -->
                    <div class="span4">
                        <select id="issue-status">
                            <option value=""><?php echo $localization['dashboard.issues.issue-status']; ?></option>
                        <?php foreach ( $issueStatusList as $issueStatus ): ?>
                            <option value="<?php echo $issueStatus['issueStatusSlug']; ?>"><?php echo $issueStatus['issueStatusName']; ?></option>
                        <?php endforeach; ?>
                        </select>
                    </div> <!-- .span4 -->
                </div> <!-- .row-fluid -->
                <p id="no-issues" class="hide"><?php echo $localization['dashboard.submitted-issues.no-issues']; ?></p>
                <p id="loading" class="text-center"><img src="<?php echo $cdnUrl; ?>/img/loading.gif" alt=""></p>
                <ul id="issues"></ul>
                <div id="pagination" class="pagination text-center">
                    <ul></ul>
                </div> <!-- #pagination -->
            </div> <!-- #main-content -->
        </div> <!-- .span8 -->
    </div> <!-- .row-fluid -->
</div> <!-- .container -->

<script type="text/javascript">
    $.when(
        $.getScript('<?php echo $cdnUrl; ?>/js/moment.min.js'),
        $.getScript('<?php echo $cdnUrl; ?>/js/markdown.min.js'),
        $.Deferred(function(deferred) {
            $(deferred.resolve);
        })
    ).done(function() {
        moment.locale('<?php echo $language; ?>');

        converter = Markdown.getSanitizingConverter();
        $('.markdown').each(function() {
            var plainContent    = $(this).text(),
                markdownContent = converter.makeHtml(plainContent.replace(/\\n/g, '\n'));
            
            $(this).html(markdownContent);
        });
       
        getIssues();
    });
</script>
<script type="text/javascript">
    $('#issue-filter').click(function() {
        return getIssues();
    });
</script>
<script type="text/javascript">
    $('#pagination > ul').delegate('li', 'click', function(e) {
        e.preventDefault();
        if ( $(this).hasClass('disabled') ) {
            return;
        }
        var currentPage = parseInt($('li.active > a', '#pagination > ul').html());
        
        $('#pagination > li.active').removeClass('active');
        $(this).addClass('active');
        var pageNumber  = $('a', this).html();

        if ( pageNumber === '&lt;' ) {
            pageNumber  = currentPage - 1;
        } else if ( pageNumber === '&gt;' ) {
            pageNumber  = currentPage + 1;
        }
        getIssues(pageNumber);
    });
</script>
<script type="text/javascript">
    function getIssues(pageNumber) {
        var productId     = $('#product').val(),
            issueCategory = $('#issue-category').val(),
            issueStatus   = $('#issue-status').val();

        if ( typeof(pageNumber) == 'undefined' ) {
            pageNumber = 1;
        }
        $('#no-issues').addClass('hide');
        $('#issues').addClass('hide');
        $('#pagination').addClass('hide');
        $('#loading').removeClass('hide');
        return getIssuesAction(productId, issueCategory, issueStatus, pageNumber);
    }
</script>
<script type="text/javascript">
    function getIssuesAction(productId, issueCategory, issueStatus, pageNumber) {
        var pageRequest = {
            'product': productId,
            'issueCategory': issueCategory,
            'issueStatus': issueStatus,
            'page': pageNumber,
        };
        $.ajax({
            type: 'GET',
            url: '<?php echo $this->url->get('/dashboard/getReceivedIssues.action'); ?>',
            data: pageRequest,
            dataType: 'JSON',
            success: function(result){
                return processResult(result, pageNumber);
            }
        });
    }
</script>
<script type="text/javascript">
    function processResult(result, pageNumber) {
        $('#loading').addClass('hide');

        if ( !result['isSuccessful'] ) {
            $('#no-issues').removeClass('hide');
        } else {
            $('#issues').removeClass('hide');
            $('#pagination').removeClass('hide');
            displayIssues(result['issues'])
            displayPagination(pageNumber, result['totalPages']);
        }
    }
</script>
<script type="text/javascript">
    function displayIssues(issues) {
        $('#issues').empty();

        for ( var i = 0; i < issues.length; ++ i ) {
            $('#issues').append(
                getIssueContent(issues[i])
            );
        }
    }
</script>
<script type="text/javascript">
    function getIssueContent(issue) {
        var issueTemplate = '<li class="issue row-fluid" data-value="%s">' +
                            '    <div class="span10">' +
                            '        <h5><a href="<?php echo $this->url->get('/issue/'); ?>%s">%s</a></h5>' +
                            '        <ul class="inline">' +
                            '            <li><i class="fa fa-hdd-o"></i> %s</li>' +
                            '            <li><i class="fa fa-list"></i> %s</li>' +
                            '            <li><i class="fa fa-caret-square-o-down"></i> %s</li>' +
                            '            <li><i class="fa fa-clock-o"></i> %s</li>' +
                            '        </ul>' + 
                            '    </div> <!-- .span10 -->' +
                            '    <div class="issue-reply span2 text-right">' + 
                            '        <i class="fa fa-comments"></i> %s' +
                            '    </div> <!-- .span2 -->' +
                            '</li>';

        return issueTemplate.format(issue['issueId'], issue['issueId'], issue['issueTitle'],
                issue['product']['productName'], issue['issueCategory']['issueCategoryName'], 
                issue['issueStatus']['issueStatusName'], getTimeElapsed(issue['createTime']), 
                issue['issueRepliesCount']);
    }
</script>
<script type="text/javascript">
    function getTimeElapsed(dateTimeString) {
        var dateTime = moment(dateTimeString);
        return dateTime.fromNow();
    }
</script>
<script type="text/javascript">
    function displayPagination(currentPage, totalPages) {
        $('#pagination > ul').empty();

        var lowerBound = currentPage - 5 > 0 ? currentPage - 5 : 1,
            upperBound = currentPage + 5 < totalPages ? currentPage + 5 : totalPages;
            paginationString  = '<li class="previous ' + ( currentPage > 1 ? '' : 'disabled') + '"><a href="#">&lt;</a></li>';

        for ( var i = lowerBound; i <= upperBound; ++ i ) {
            paginationString += '<li' + ( currentPage == i ? ' class="active"' : '' ) + '><a href="#">' + i + '</a></li>';
        }
        paginationString     += '<li class="next ' + ( currentPage < totalPages ? '' : 'disabled') + '"><a href="#">&gt;</a></li>';
        $('#pagination > ul').append(paginationString);
    }
</script>