language: java
jdk:
  - oraclejdk8
  - openjdk7
  - oraclejdk7

services: mysql

before_script:
  - mysql -e 'CREATE DATABASE test;'
  - mysql test < testzilla.sql

script: mvn test

after_script:
  - mysql -e 'DROP DATABASE test;'
