<div style="background:#fff; font-family:'Segoe UI', 'Microsoft YaHei'; margin:0; padding:0; width:100%;">
<table align="center" width="625" cellspacing="0" cellpadding="0" border="0">
    <tbody>
        <tr>
            <td style="padding: 0 0 35px; text-align: left; max-height: 40px;">
                <img src="<?php echo $baseUrl; ?>/img/logo.png" alt="Logo" style="max-height: 40px;" />
            </td>
        </tr>
        <tr>
            <td style="color: #484848; font-size: 18px; line-height: 24px; padding: 0 30px 35px 0;">
                Great,<br><br>

                <?php echo $username; ?>, now TestZilla is ready to use.<br>
                Please verify your email address with the link below to get started. It will remain active for 24 hours.
            </td>
        </tr>
        <tr>
            <td>
                <a href="<?php echo $baseUrl; ?>/accounts/verify-email?email=<?php echo $email; ?>&token=<?php echo $token; ?>" style="background-color: #3498db; border: 0; color: #fff; display: block; padding: 9px 12px 10px; line-height: 22px; margin: 0 0 20px; width: 150px; text-align: center; text-decoration: none; border-radius: 6px;" target="_blank">Verify Email Address</a>
            </td>
        </tr>
        <tr>
            <td style="color: #484848; font-size: 18px; line-height: 24px; padding: 0 30px 35px 0;">
                Thank you,<br>
                TestZilla Team
            </td>
        </tr>
        <tr>
            <td style="text-align: center; padding: 30px 0 10px; font-size: 12px;">
                <p style="border-top: 1px solid #bbb; border-bottom: 1px solid #bbb; padding: 15px 5px 15px 5px;">
                    <a href="<?php echo $baseUrl; ?>/accounts/signin" target="_blank" style="color:#2980b9; text-decoration:none;">Accounts</a>
                    <span style="padding:20px 15px;color:#848484">&bull;</span>
                    <a href="<?php echo $baseUrl; ?>/privacy" target="_blank" style="color:#2980b9; text-decoration:none;">Privacy &amp; Cookies</a>
                    <span style="padding:20px 15px;color:#848484">&bull;</span>
                    <a href="<?php echo $baseUrl; ?>/terms" target="_blank" style="color:#2980b9; text-decoration:none;">Terms of Use</a>
                </p>
            </td>
        </tr>
        <tr>
            <td style="color: #535353; font-size: 12px; line-height: 16px; text-align: center;">
                This email has been sent to you by <a href="<?php echo $baseUrl; ?>" target="_blank" style="color:#2980b9; text-decoration:none;">TestZilla</a>.<br>
                Follow us on <a href="https://github.com/zjhzxhz/TestZilla" target="_blank" style="color: #2980b9; text-decoration: none;">GitHub@TestZilla</a>
            </td>
        </tr>
    </tbody>
</table>
</div>