<div id="header">
    <div class="container">
        <div class="row-fluid">
            <div id="logo" class="span4">
                <a href="<?php echo $this->url->get(''); ?>">
                    <img src="<?php echo $cdnUrl; ?>img/logo.png" alt="Logo" />
                </a>
            </div> <!-- #logo -->
            <div id="nav" class="span8">
                <ul class="inline">
                    <li><a href="<?php echo $this->url->get(''); ?>">Home</a></li>
                    <li><a href="<?php echo $this->url->get('products'); ?>">Products</a></li>
                    <li><a href="<?php echo $this->url->get('contests'); ?>">Contests</a></li>
                    <li><button class="btn btn-primary" onclick="window.location.href='<?php echo $this->url->get('accounts/signin'); ?>'">Sign in</button></li>
                </ul>
            </div> <!-- #nav -->
        </div> <!-- .row-fluid -->
    </div> <!-- .container -->
</div> <!-- #header -->
<div id="content">
	<?php echo $this->getContent(); ?>
</div> <!-- #content -->
<div id="footer">
    <div class="container">
        <div class="row-fluid">
            <div class="span3">
                <p>Block A</p>
            </div> <!-- .span3 -->
            <div class="span3">
                <p>Block B</p>
            </div> <!-- .span3 -->
            <div class="span6">
                <p>Block C</p>
            </div> <!-- .span6 -->
        </div> <!-- .row-fluid -->
    </div> <!-- .container -->
</div> <!-- #footer -->
