<!DOCTYPE html>
<html lang="<?php echo $language; ?>">
<head>
    <meta charset="UTF-8">
    <title><?php echo Phalcon\Tag::getTitle(); ?></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="<?php echo $cdnUrl; ?>/favicon.ico" />
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="<?php echo $cdnUrl; ?>/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $cdnUrl; ?>/css/bootstrap-responsive.min.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $cdnUrl; ?>/css/flat-ui.min.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $cdnUrl; ?>/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $cdnUrl; ?>/css/style.css?ver=<?php echo $appVerion; ?>" />
    <!-- Java Script -->
    <script type="text/javascript" src="<?php echo $cdnUrl; ?>/js/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="<?php echo $cdnUrl; ?>/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="<?php echo $cdnUrl; ?>/js/site.js?ver=<?php echo $appVerion; ?>"></script>
</head>
<body>
    <?php echo $this->getContent(); ?>
</body>
</html>