<?php echo Phalcon\Tag::stylesheetLink("{$cdnUrl}/css/accounts/reset-password.css?ver={$appVerion}"); ?>
<div id="reset-password">
    <h2><?php echo $localization['accounts.reset-password.reset-password']; ?></h2>
    <div class="alert alert-error hide"></div> <!-- .alert-error -->
    <div class="alert alert-success hide"></div> <!-- .alert-success -->
<?php if ( isset($isTokenValid) && $isTokenValid ): ?>
    <form id="reset-password-form" method="POST" onSubmit="onSubmit(); return false;">
        <p class="row-fluid">
            <label for="email"><?php echo $localization['accounts.reset-password.email'] ?></label>
            <input id="email" name="email" class="span12" type="text" value="<?php echo $email; ?>" maxlength="64" disabled="disabled" />
        </p>
        <p class="row-fluid">
            <label for="new-password"><?php echo $localization['accounts.reset-password.new-password']; ?></label>
            <input id="new-password" name="new-password" class="span12" type="password" maxlength="16" />
        </p>
        <p class="row-fluid">
            <label for="confirm-new-password"><?php echo $localization['accounts.reset-password.confirm-new-password']; ?></label>
            <input id="confirm-new-password" name="confirm-new-password" class="span12" type="password" maxlength="16" />
        </p>
        <p>
            <input id="csrf-token" name="<?php echo $this->security->getTokenKey(); ?>" value="<?php echo $this->security->getToken(); ?>" type="hidden" />
            <button class="btn btn-primary btn-block" type="submit"><?php echo $localization['accounts.reset-password.reset-password']; ?></button>
        </p>
    </form> <!-- #reset-password-form -->
<?php else: ?>
    <form id="reset-password-form" method="POST" onSubmit="onSubmit(); return false;">
        <p class="row-fluid">
            <label for="username"><?php echo $localization['accounts.reset-password.username'] ?></label>
            <input id="username" name="username" class="span12" type="text" maxlength="16" />
        </p>
        <p class="row-fluid">
            <label for="email"><?php echo $localization['accounts.reset-password.email'] ?></label>
            <input id="email" name="email" class="span12" type="text" maxlength="64" />
        </p>
        <p>
            <input id="csrf-token" name="<?php echo $this->security->getTokenKey(); ?>" value="<?php echo $this->security->getToken(); ?>" type="hidden" />
            <button class="btn btn-primary btn-block" type="submit"><?php echo $localization['accounts.reset-password.send-verification-email']; ?></button>
        </p>
    </form> <!-- #reset-password-form -->
<?php endif; ?>
</div> <!-- #reset-password -->

<?php if ( isset($isTokenValid) && $isTokenValid ): ?>
<script type="text/javascript">
    function onSubmit() {
        $('.alert-error').addClass('hide');
        $('button[type=submit]').attr('disabled', 'disabled');
        $('button[type=submit]').html('<?php echo $localization['accounts.reset-password.please-wait']; ?>');

        var email           = '<?php echo $email; ?>',
            token           = '<?php echo $token; ?>',
            newPassword     = $('#new-password').val()
            confirmPassword = $('#confirm-new-password').val(),
            csrfKey         = $('#csrf-token').attr('name'),
            csrfValue       = $('#csrf-token').val();

        return doResetPasswordAction(email, token, newPassword, confirmPassword, csrfKey, csrfValue);
    }
</script>
<script type="text/javascript">
    function doResetPasswordAction(email, token, newPassword, confirmPassword, csrfKey, csrfValue) {
        var postData = {
            'email': email,
            'token': token,
            'newPassword': newPassword,
            'confirmPassword': confirmPassword
        };
        postData[csrfKey] = csrfValue;

        $.ajax({
            type: 'POST',
            url: '<?php echo $this->url->get('/accounts/resetPassword.action'); ?>',
            data: postData,
            dataType: 'JSON',
            success: function(result){
                return processResult(result);
            }
        });
    }
</script>
<script type="text/javascript">
    function processResult(result) {
        if ( result['isSuccessful'] ) {
            $('.alert-success').html('<?php echo $localization['accounts.reset-password.password-resetted']; ?>');
            $('.alert-success').removeClass('hide');
            $('#reset-password-form').addClass('hide');
        } else {
            var errorMessage  = '';

            if ( !result['isCsrfTokenValid'] ) {
                errorMessage += '<?php echo $localization['accounts.reset-password.invalid-csrf-token']; ?><br>';
            }
            if ( !result['isEmailValidationValid'] ) {
                errorMessage += '<?php echo $localization['accounts.reset-password.invalid-email-token']; ?><br>';
            }
            if ( result['isNewPasswordEmpty'] ) {
                errorMessage += '<?php echo $localization['accounts.reset-password.new-password-empty']; ?><br>';
            } else if ( !result['isNewPasswordLegal'] ) {
                errorMessage += '<?php echo $localization['accounts.reset-password.new-password-illegal']; ?><br>';
            }
            if ( !result['isConfirmPasswordMatched'] ) {
                errorMessage += '<?php echo $localization['accounts.reset-password.new-password-not-matched']; ?><br>';
            }
            $('.alert-error').html(errorMessage);
            $('.alert-error').removeClass('hide');
        }

        $('button[type=submit]').html('<?php echo $localization['accounts.reset-password.reset-password']; ?>');
        $('button[type=submit]').removeAttr('disabled');
    }
</script>
<?php elseif ( isset($isTokenSet) && $isTokenSet ): ?>
<script type="text/javascript">
    $(function() {
        $('.alert-error').html('<?php echo $localization['accounts.reset-password.invalid-email-token']; ?>');
        $('.alert-error').removeClass('hide');
        $('#reset-password-form').addClass('hide');
    });
</script>
<?php else: ?>
<script type="text/javascript">
    function onSubmit() {
        $('.alert-error').addClass('hide');
        $('button[type=submit]').attr('disabled', 'disabled');
        $('button[type=submit]').html('<?php echo $localization['accounts.reset-password.please-wait']; ?>');
        
        var username    = $('#username').val(),
            email       = $('#email').val(),
            csrfKey     = $('#csrf-token').attr('name'),
            csrfValue   = $('#csrf-token').val();

        return doResetPasswordAction(username, email, csrfKey, csrfValue);
    }
</script>
<script type="text/javascript">
    function doResetPasswordAction(username, email, csrfKey, csrfValue) {
        var postData = {
            'username': username,
            'email': email,
        };
        postData[csrfKey] = csrfValue;

        $.ajax({
            type: 'POST',
            url: '<?php echo $this->url->get('/accounts/forgotPassword.action'); ?>',
            data: postData,
            dataType: 'JSON',
            success: function(result){
                return processResult(result);
            }
        });
    }
</script>
<script type="text/javascript">
    function processResult(result) {
        if ( result['isSuccessful'] ) {
            $('.alert-success').html('<?php echo $localization['accounts.reset-password.mail-sent']; ?>');
            $('.alert-success').removeClass('hide');
            $('#reset-password-form').addClass('hide');
        } else {
            var errorMessage  = '';

            if ( !result['isCsrfTokenValid'] ) {
                errorMessage += '<?php echo $localization['accounts.reset-password.invalid-csrf-token']; ?><br>';
            } else if ( !result['isUserExists'] ) {
                errorMessage += '<?php echo $localization['accounts.reset-password.user-not-exists']; ?><br>';
            }
            $('.alert-error').html(errorMessage);
            $('.alert-error').removeClass('hide');
        }

        $('button[type=submit]').html('<?php echo $localization['accounts.reset-password.send-verification-email']; ?>');
        $('button[type=submit]').removeAttr('disabled');
    }
</script>
<?php endif; ?>